name: Haskell CI

on: [push, pull_request]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mstksg/setup-stack@v2
    - name: Build & Test
      run: ~/.local/bin/stack --no-terminal test --fast
